export const ActionTypes = {
    SET_MODE: 'SET_MODE',
    SET_PLAYER_NAMES: 'SET_PLAYER_NAMES',
    HANDLE_MOVE: 'HANDLE_MOVE',
    SET_PLAYING_ONLINE: 'SET_PLAYING_ONLINE',
    JOIN_ROOM: 'JOIN_ROOM',
    UPDATE_STATE: 'UPDATE_STATE',
    SET_LOADING: 'SET_LOADING',
    START_OVER: 'START_OVER',
    CLEAR_BOARD: 'CLEAR_BOARD',
}
