const iconMap = {
    anime: 'custom:anime',
    arrowOpenLeft: 'line-md:arrow-open-left',
    arrowOpenRight: 'line-md:arrow-open-right',
    broom: 'game-icons:broom',
    card: 'material-symbols:cards-outline-rounded',
    close: 'iconamoon:close',
    closeAnimated: 'line-md:close-small',
    desktop: 'noto:desktop-computer',
    down: 'formkit:down',
    edit: 'hugeicons:pencil-edit-02',
    editProfile: 'fluent:person-edit-24-filled',
    email: 'line-md:email-alt-filled',
    error: 'meteocons:code-red-fill',
    filePlus: 'line-md:file-plus-filled',
    filter: 'line-md:filter-filled',
    gamePad: 'emojione-monotone:video-game',
    gamePadTurbo: 'arcticons:gameturbo',
    google: 'logos:google-icon',
    heart: 'icomoon-free:heart',
    info: 'ic:round-info',
    infoOutlined: 'carbon:information',
    left: 'formkit:left',
    leftArrow: 'line-md:arrow-left',
    list: 'tabler:list',
    loading: 'line-md:loading-loop',
    logOut: 'majesticons:logout',
    manga: 'custom:manga',
    minus: 'line-md:minus',
    moon: 'meteocons:clear-night-fill',
    moreDots: 'pepicons-pop:dots-y',
    music: 'solar:music-note-bold',
    password: 'line-md:watch-loop',
    person: 'line-md:person-filled',
    player: 'game-icons:centurion-helmet',
    plus: 'line-md:plus',
    right: 'formkit:right',
    rightArrow: 'line-md:arrow-right',
    refresh: 'grommet-icons:power-reset',
    search: 'line-md:search',
    settings: 'solar:settings-bold',
    settingsOutlined: 'solar:settings-outline',
    share: 'solar:share-bold-duotone',
    showPassword: 'line-md:watch-off-loop',
    spotify: 'line-md:spotify-filled',
    success: 'line-md:confirm-circle-filled',
    sun: 'meteocons:clear-day-fill',
    trash: 'entypo:trash',
    up: 'formkit:up',
    upload: 'line-md:cloud-alt-upload-filled-loop',
    user: 'carbon:user-avatar-filled',
    warning: 'meteocons:code-yellow-fill',
    // warning: 'solar:shield-warning-bold',
}

export default iconMap
