import ROUTES from '../constants/routes';

export const iconMap = {
    anime: 'custom:anime',
    broom: 'game-icons:broom',
    card: 'material-symbols:cards-outline-rounded',
    close: 'iconamoon:close',
    closeAnimated: 'line-md:close-small',
    desktop: 'noto:desktop-computer',
    down: 'formkit:down',
    email: 'line-md:email-alt-filled',
    error: 'meteocons:code-red-fill',
    filePlus: 'line-md:file-plus-filled',
    gamePad: 'emojione-monotone:video-game',
    gamePadTurbo: 'arcticons:gameturbo',
    google: 'logos:google-icon',
    heart: 'icomoon-free:heart',
    info: 'ic:round-info',
    infoOutlined: 'carbon:information',
    list: 'tabler:list',
    loading: 'line-md:loading-loop',
    logOut: 'majesticons:logout',
    manga: 'custom:manga',
    moon: 'meteocons:clear-night-fill',
    moreDots: 'pepicons-pop:dots-y',
    music: 'solar:music-note-bold',
    password: 'line-md:watch-loop',
    person: 'line-md:person-filled',
    player: 'game-icons:centurion-helmet',
    refresh: 'grommet-icons:power-reset',
    search: 'line-md:search',
    settings: 'solar:settings-bold',
    settingsOutlined: 'solar:settings-outline',
    share: 'solar:share-bold-duotone',
    showPassword: 'line-md:watch-off-loop',
    success: 'line-md:confirm-circle-filled',
    sun: 'meteocons:clear-day-fill',
    trash: 'entypo:trash',
    up: 'formkit:up',
    upload: 'line-md:cloud-alt-upload-filled-loop',
    user: 'carbon:user-avatar-filled',
    warning: 'meteocons:code-yellow-fill',
    // warning: 'solar:shield-warning-bold',
}

export const sidenavMenuItems = [
    {
        title: 'Anime Hub',
        icon: iconMap.anime,
        children: [
            { name: 'Anime Hub', link: ROUTES.ANIME_HUB },
            { name: 'Authorize', link: ROUTES.ANIME_HUB_AUTH },
        ],
    },
    {
        title: 'Games',
        icon: iconMap.gamePad,
        children: [
            {
                name: 'Tic Tac Toe',
                children: [
                    { name: 'Classic', link: ROUTES.CLASSIC_TIC_TAC_TOE },
                    { name: 'Ultimate', link: ROUTES.ULTIMATE_TIC_TAC_TOE },
                ],
            },
            { name: 'Snake', link: '/games/snake' },
            { name: 'Ludo', link: '/games/ludo' },
        ],
    },
    {
        title: 'Audio',
        icon: iconMap.music,
        children: [{ name: 'Music Editor', link: ROUTES.AUDIO_TAGS_EXTRACTOR }],
    },
    {
        title: 'Profile',
        badge: 14,
        icon: iconMap.person,
        link: '/profile',
    },
];
